import java.util.*;
import java.util.stream.Collectors;

public class ModernJavaDemo {

    // Records (Java 16): immutable data class, compiler generates everything
    record Point(int x, int y) {
        // Compact constructor: validation added here
        Point {
            if (x < 0 || y < 0) throw new IllegalArgumentException("Coordinates must be non-negative");
        }

        // Custom methods work fine in records
        public double distanceTo(Point other) {
            int dx = this.x - other.x;
            int dy = this.y - other.y;
            return Math.sqrt(dx * dx + dy * dy);
        }

        public Point translate(int dx, int dy) {
            return new Point(x + dx, y + dy); // records are immutable, return new instance
        }
    }

    // Sealed class (Java 17): only these three can implement Shape
    sealed interface Shape permits Circle, Rectangle, Triangle {}

    record Circle(double radius) implements Shape {}
    record Rectangle(double width, double height) implements Shape {}
    record Triangle(double base, double height) implements Shape {}

    public static void main(String[] args) {
        records();
        collectionFactories();
        varKeyword();
        sealedAndSwitch();
        textBlocks();
        patternMatching();
    }

    static void records() {
        System.out.println("=== Records ===");

        Point p1 = new Point(3, 4);
        Point p2 = new Point(0, 0);

        System.out.println("p1: " + p1);               // Point[x=3, y=4]
        System.out.println("x=" + p1.x() + ", y=" + p1.y()); // accessor methods

        // Structural equality (generated by compiler)
        Point p3 = new Point(3, 4);
        System.out.println("p1.equals(p3): " + p1.equals(p3)); // true
        System.out.println("p1 == p3: " + (p1 == p3));           // false (different objects)

        // Custom methods
        System.out.printf("Distance p2 to p1: %.2f%n", p2.distanceTo(p1)); // 5.00
        System.out.println("Translate: " + p1.translate(1, -1)); // Point[x=4, y=3]

        // Records work great in collections
        Set<Point> points = new HashSet<>(Set.of(new Point(1, 2), new Point(3, 4)));
        System.out.println("Contains (1,2): " + points.contains(new Point(1, 2))); // true

        // Validation in compact constructor
        try {
            new Point(-1, 5);
        } catch (IllegalArgumentException e) {
            System.out.println("Caught: " + e.getMessage());
        }
    }

    static void collectionFactories() {
        System.out.println("\n=== Collection Factory Methods (Java 9+) ===");

        List<String> names = List.of("Alice", "Bob", "Charlie");
        Set<Integer> ids = Set.of(1, 2, 3);
        Map<String, Integer> scores = Map.of("Alice", 95, "Bob", 87);

        System.out.println("List: " + names);
        System.out.println("Set: " + ids);
        System.out.println("Map: " + scores);

        // These are immutable:
        try {
            names.add("Diana");
        } catch (UnsupportedOperationException e) {
            System.out.println("List.of is immutable: " + e.getClass().getSimpleName());
        }

        // Mutable copy:
        List<String> mutable = new ArrayList<>(names);
        mutable.add("Diana");
        System.out.println("Mutable copy: " + mutable);
    }

    static void varKeyword() {
        System.out.println("\n=== var (Java 10) ===");

        var list = new ArrayList<String>();   // inferred: ArrayList<String>
        list.add("hello");
        list.add("world");

        var map = new HashMap<String, Integer>();
        map.put("a", 1);

        // var in for-each
        for (var entry : map.entrySet()) {
            System.out.println(entry.getKey() + "=" + entry.getValue());
        }

        var result = list.stream()
            .filter(s -> s.length() > 4)
            .toList(); // result type: List<String>
        System.out.println("Filtered: " + result);
    }

    static void sealedAndSwitch() {
        System.out.println("\n=== Sealed Classes + Switch (Java 17/21) ===");

        List<Shape> shapes = List.of(
            new Circle(5.0),
            new Rectangle(4.0, 6.0),
            new Triangle(3.0, 8.0)
        );

        for (Shape shape : shapes) {
            // Exhaustive switch — compiler knows all possible types (sealed!)
            double area = switch (shape) {
                case Circle c     -> Math.PI * c.radius() * c.radius();
                case Rectangle r  -> r.width() * r.height();
                case Triangle t   -> 0.5 * t.base() * t.height();
                // No default needed — compiler guarantees coverage
            };

            String name = shape.getClass().getSimpleName();
            System.out.printf("%s → area=%.2f%n", name, area);
        }
    }

    static void textBlocks() {
        System.out.println("\n=== Text Blocks (Java 15) ===");

        String json = """
                {
                    "name": "Alice",
                    "age": 30,
                    "active": true
                }
                """;
        System.out.print("JSON:\n" + json);

        String sql = """
                SELECT u.name, COUNT(o.id) AS order_count
                FROM users u
                LEFT JOIN orders o ON u.id = o.user_id
                WHERE u.active = true
                GROUP BY u.name
                ORDER BY order_count DESC
                """;
        System.out.print("SQL:\n" + sql);
    }

    static void patternMatching() {
        System.out.println("=== Pattern Matching instanceof (Java 16+) ===");

        Object[] objects = {"hello", 42, 3.14, List.of(1, 2, 3), null};

        for (Object obj : objects) {
            // Pattern matching: check + bind in one step
            if (obj instanceof String s) {
                System.out.println("String of length " + s.length() + ": " + s.toUpperCase());
            } else if (obj instanceof Integer i) {
                System.out.println("Integer: " + i * 2);
            } else if (obj instanceof Double d) {
                System.out.printf("Double: %.1f%n", d);
            } else if (obj instanceof List<?> l) {
                System.out.println("List with " + l.size() + " elements");
            } else if (obj == null) {
                System.out.println("null value");
            }
        }
    }
}
